spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        game-progress-event-out:
          destination: game-progress-event
          producer:
            useNativeEncoding: true
management:
  endpoint:
    health:
      show-details: always
server:
  port: 8081
